description: Unexpected error
content:
  application/json:
    schema:
      $ref: "#/components/schemas/error"
    example:
      error:
        value:
          status: 500
          message: "Internal Server Error"
