apiVersion: v1
kind: ServiceAccount
metadata:
  name: TILLER_SA_NAME
  namespace: TILLER_NAMESPACE
  
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: TILLER_ROLE_NAME
  namespace: TILLER_NAMESPACE
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: TILLER_ROLE_NAME
  namespace: HKUBE_NAMESPACE
rules:
- apiGroups: ["", "batch", "extensions", "apps", "etcd.database.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: TILLER_ROLE_BINDING_NAME
  namespace: TILLER_NAMESPACE
subjects:
- kind: ServiceAccount
  name: TILLER_SA_NAME
  namespace: TILLER_NAMESPACE
roleRef:
  kind: Role
  name: TILLER_ROLE_NAME
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: TILLER_ROLE_BINDING_NAME
  namespace: HKUBE_NAMESPACE
subjects:
- kind: ServiceAccount
  name: TILLER_SA_NAME
  namespace: TILLER_NAMESPACE
roleRef:
  kind: Role
  name: TILLER_ROLE_NAME
  apiGroup: rbac.authorization.k8s.io

