const { gql } = require('apollo-server');

const algorithmTypeDefs = gql`
type Options { debug: Boolean pending: Boolean }

type Commit { id: String timestamp: String message: String }

type GitRepository { gitKind: String
  url: String
  branchName: String
  webUrl: String
  cloneUrl: String
  commit: Commit }

type Algorithm { 
 
  name: String
  cpu: String
  created: Float
  entryPoint: String
  env: String
  gpu: String
  mem: String
  minHotWorkers: Int
  modified: Float
  reservedMemory: String
  type: String
  algorithmImage: String
  version: String
  options: Options
  gitRepository: GitRepository
  buildStats: BuildStatsForAlgorithm
   }

type AutogeneratedMainType { algorithms: [Algorithm ] }

extend type Query {
    
    algorithms:[Algorithm]
    algorithmsByName(name: String!): Algorithm
}

`;

module.exports = algorithmTypeDefs;
