type: object
properties:
  name:
    $ref: "#/components/schemas/pipelineName"
  description:
    type: string
    description: pipeline description
  nodes:
    type: array
    description: Array of nodes
    items:
      $ref: "#/components/schemas/pipelineNode"
  flowInput:
    type: object
    description: input object
  webhooks:
    $ref: "#/components/schemas/webhooks"
  options:
    $ref: "#/components/schemas/options"
    default: {}
  priority:
    $ref: "#/components/schemas/priority"
    default: 3
  triggers:
    $ref: "#/components/schemas/triggers"
additionalProperties: false
required:
  - name
  - nodes
