module.exports = {
    QUERIER: 'QUERIER',
    QUEUE: 'QUEUE',
    QUEUE_RUNNER: 'QUEUE_RUNNER',
    BOOTSTRAP: 'BOOTSTRAP',
    HEURISTIC_RUNNER: 'HEURISTIC_RUNNER',
    MAIN: 'MAIN',
    PERSISTENT: 'PERSISTENT',
    REDIS_PERSISTENT: 'REDIS_PERSISTENT',
    JOBS_PRODUCER: 'JOBS_PRODUCER',
    JOBS_CONSUMER: 'JOBS_CONSUMER',
    AGGREGATION_METRIC: 'AGGREGATION_METRIC',
    DB: 'DB'
};
