openapi: 3.0.0
info:
  $ref: ./swagger/info/index.yaml
tags:
  $ref: ./swagger/tags/index.yaml
externalDocs:
  description: Find out more about Hkube
  url: "http://hkube.io"
servers: []
paths:
  $ref: ./swagger/paths/index.yaml
components:
  schemas:
    $ref: ./swagger/components/schemas/index.yaml
  parameters:
    $ref: ./swagger/paths/datasource/parameters.yaml
  responses:
    $ref: ./swagger/components/responses/index.yaml
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
  - {}