# algorithms
algorithm:
  $ref: ./algorithms/algorithm.yaml
algorithmKind:
  $ref: ./algorithms/algorithmKind.yaml
algorithmName:
  $ref: ./algorithms/algorithmName.yaml
algorithmNameObject:
  $ref: ./algorithms/algorithmNameObject.yaml
algorithmDelete:
  $ref: ./algorithms/algorithmDelete.yaml
algorithmImage:
  $ref: ./algorithms/algorithmImage.yaml
algorithmMount:
  $ref: ./algorithms/algorithmMount.yaml
algorithmEnv:
  $ref: ./algorithms/algorithmEnv.yaml
algorithmFileExt:
  $ref: ./algorithms/algorithmFileExt.yaml
algorithmVersionId:
  $ref: ./algorithms/algorithmVersionId.yaml
applyAlgorithmVersion:
  $ref: ./algorithms/applyAlgorithmVersion.yaml
algorithmVersionTag:
  $ref: ./algorithms/algorithmVersionTag.yaml
algorithmApplyOptions:
  $ref: ./algorithms/algorithmApplyOptions.yaml
algorithmApplyResponse:
  $ref: ./algorithms/algorithmApplyResponse.yaml
algorithmBuild:
  $ref: ./algorithms/algorithmBuild.yaml
kubernetesValueFrom:
  $ref: ./algorithms/kubernetesValueFrom.yaml
sideCars:
  $ref: ./algorithms/sideCars.yaml
sidecarContainer:
  $ref: ./algorithms/sidecarContainer.yaml
sidecarVolumeMounts:
  $ref: ./algorithms/sidecarVolumeMounts.yaml  
sidecarEnvVars:
  $ref: ./algorithms/sidecarEnvVars.yaml 
sidecarVolume: 
  $ref: ./algorithms/sidecarVolume.yaml
sidecarResourceRequests:
  $ref: ./algorithms/sidecarResourceRequests.yaml
sidecarLimits:
  $ref: ./algorithms/sidecarLimits.yaml
sidecarRequests:
  $ref: ./algorithms/sidecarRequests.yaml

# boards
createBoardRequest:
  $ref: ./boards/createBoardRequest.yaml
createOptunaboardRequest:
  $ref: ./boards/createOptunaboardRequest.yaml  
createBoardResponse:
  $ref: ./boards/createBoardResponse.yaml
getBoardResponse:
  $ref: ./boards/getBoardResponse.yaml
listBoardResponse:
  $ref: ./boards/listBoardResponse.yaml
metrics:
  $ref: ./boards/metrics.yaml

#preferred
addToPreferredRequest:
  $ref: ./preferred/addToPreferredRequest.yaml
removeFromPreferredRequest:
  $ref: ./preferred/removeFromPreferredRequest.yaml
preferredQuery:
  $ref: ./preferred/preferredQuery.yaml

#queue
queueCountResponse:
  $ref: ./queue/queueCountResponse.yaml

#jobsAggregation
jobsAggregationResponse:
  $ref: ./aggregation/jobsAggregationResponse.yaml

# builds
buildId:
  $ref: ./builds/buildId.yaml
buildIdObject:
  $ref: ./builds/buildIdObject.yaml

# common
defaultResponse:
  $ref: ./common/defaultResponse.yaml
defaultResponseWithName:
  $ref: ./common/defaultResponseWithName.yaml
error:
  $ref: ./common/error.yaml
jobId:
  $ref: ./common/jobId.yaml
jobIdObject:
  $ref: ./common/jobIdObject.yaml
jobListItem:
  $ref: ./exec/jobListItem.yaml
tag:
  $ref: ./common/tag.yaml
queryList:
  $ref: ./common/queryList.yaml
queryRange:
  $ref: ./common/queryRange.yaml

# cron
cronPattern:
  $ref: ./cron/cronPattern.yaml
cronRequest:
  $ref: ./cron/cronRequest.yaml

# datasource
dataSource-name:
  $ref: ./datasource/dataSource-name.yaml
dataSource-snapshot:
  $ref: ./datasource/dataSource-snapshot.yaml
dataSource-id:
  $ref: ./datasource/dataSource-id.yaml
Files:
  $ref: ./datasource/Files.yaml
FileMeta:
  $ref: ./datasource/FileMeta.yaml
Error:
  $ref: ./datasource/Error.yaml
DataSourceMeta:
  $ref: ./datasource/DataSourceMeta.yaml
DataSource:
  $ref: ./datasource/DataSource.yaml
DataSourceId:
  $ref: ./datasource/DataSourceId.yaml
DataSourceWithMeta:
  $ref: ./datasource/DataSourceWithMeta.yaml
DataSourceName:
  $ref: ./datasource/DataSourceName.yaml
DataSourceVersion:
  $ref: ./datasource/DataSourceVersion.yaml
VersionDescription:
  $ref: ./datasource/VersionDescription.yaml
dataSourceExists:
  $ref: ./datasource/dataSourceExists.yaml
SnapshotName:
  $ref: ./datasource/SnapshotName.yaml
SnapshotQuery:
  $ref: ./datasource/SnapshotQuery.yaml
SnapshotRequest:
  $ref: ./datasource/Snapshot.request.yaml
SnapshotCreate:
  $ref: ./datasource/Snapshot.create.yaml
Snapshot:
  $ref: ./datasource/Snapshot.yaml
ResolvedSnapshot:
  $ref: ./datasource/ResolvedSnapshot.yaml
SnapshotPreviewRequest:
  $ref: ./datasource/snapshotPreview.request.yaml
createRequest:
  $ref: ./datasource/create.request.yaml
updateRequest:
  $ref: ./datasource/update.request.yaml
deleteRequest:
  $ref: ./datasource/delete.request.yaml
update:
  $ref: ./datasource/update.yaml
syncRequest:
  $ref: ./datasource/sync.request.yaml
CreateDownloadLinkRequest:
  $ref: ./datasource/DownloadLink.request.yaml
DownloadId:
  $ref: ./datasource/DownloadId.yaml
Credentials:
  $ref: ./datasource/Credentials.yaml
updateCredentials:
  $ref: ./datasource/updateCredentials.yaml
URL:
  $ref: ./datasource/URL.yaml
GitURL:
  $ref: ./datasource/GitURL.yaml

# exec
caching:
  $ref: ./exec/caching.yaml
execTreeNode:
  $ref: ./exec/execTreeNode.yaml
execTreeResult:
  $ref: ./exec/execTreeResult.yaml
stopRequest:
  $ref: ./exec/stopRequest.yaml
pauseRequest:
  $ref: ./exec/pauseRequest.yaml
resumeRequest:
  $ref: ./exec/resumeRequest.yaml
execAlgorithmRequest:
  $ref: ./exec/execAlgorithmRequest.yaml
searchJobs:
  $ref: ./exec/searchJobs.yaml
searchJobsResponse:
  $ref: ./exec/searchJobsResponse.yaml
rerun:
  $ref: ./exec/rerun.yaml

# experiment
experiment:
  $ref: ./experiment/experiment.yaml
experimentName:
  $ref: ./experiment/experimentName.yaml

# gateway
gatewayName:
  $ref: ./gateway/gatewayName.yaml
gateway:
  $ref: ./gateway/gateway.yaml

output:
  $ref: ./output/output.yaml

hyperparamsTuner:
  $ref: ./hyperparamsTuner/hyperparamsTuner.yaml  
hyperparamsTunerName:
  $ref: ./hyperparamsTuner/hyperparamsTunerName.yaml  
hyperparamsTunerSpec:
  $ref: ./hyperparamsTuner/hyperparamsTunerSpec.yaml      
hyperParams:
  $ref: ./hyperparamsTuner/hyperParam.yaml  
sampler:
  $ref: ./hyperparamsTuner/sampler.yaml

# GC
clean:
  $ref: ./gc/clean.yaml
gcError:
  $ref: ./gc/error.yaml
response:
  $ref: ./gc/response.yaml

# graph
graphQuery:
  $ref: ./graph/graphQuery.yaml
graphResponse:
  $ref: ./graph/graphResponse.yaml

# pipelines
options:
  $ref: ./pipelines/options.yaml
pipeline:
  $ref: ./pipelines/pipeline.yaml
pipelineName:
  $ref: ./pipelines/pipelineName.yaml
kindPipeline:
  $ref: ./pipelines/kindPipeline.yaml
pipelineKind:
  $ref: ./pipelines/pipelineKind.yaml
nodeKind:
  $ref: ./pipelines/nodeKind.yaml
pipelineNode:
  $ref: ./pipelines/pipelineNode.yaml
pipelineResult:
  $ref: ./pipelines/pipelineResult.yaml
priority:
  $ref: ./pipelines/priority.yaml
triggers:
  $ref: ./pipelines/triggers.yaml
pipelineTriggersNode:
  $ref: ./pipelines/pipelineTriggersNode.yaml
pipelineTriggersResult:
  $ref: ./pipelines/pipelineTriggersResult.yaml
codeApiPipelineRequest:
  $ref: ./pipelines/codeApiPipelineRequest.yaml

# webhooks
webhookResult:
  $ref: ./webhooks/webhookResult.yaml
webhooks:
  $ref: ./webhooks/webhooks.yaml
githubWebhook:
  $ref: ./webhooks/githubWebhook.yaml
gitlabWebhook:
  $ref: ./webhooks/gitlabWebhook.yaml
