type: object
properties:
  name:
    type: string
  experimentName:
    $ref: "#/components/schemas/experimentName"
    default: main
  options:
    $ref: "#/components/schemas/options"
    default: {}
  priority:
    $ref: "#/components/schemas/priority"
    default: 3
required:
  - name
